import type { AnalysisResult, FileAnalysis } from "./types.js";

export function buildPrComment(result: AnalysisResult, minScore: number): string {
  const {
    qualityScore,
    aiDetected,
    aiConfidence,
    fileAnalyses,
    summary,
    passed,
    prTitle,
    filesAnalyzed,
    totalFilesInPr,
  } = result;

  const scoreEmoji = getScoreEmoji(qualityScore);
  const statusBadge = passed
    ? "![PASSED](https://img.shields.io/badge/Quality-PASSED-brightgreen)"
    : "![FAILED](https://img.shields.io/badge/Quality-FAILED-red)";

  const aiStatusBadge = aiDetected
    ? `![AI Detected](https://img.shields.io/badge/AI_Code-Detected%20(${Math.round(aiConfidence * 100)}%25)-orange)`
    : `![AI Clean](https://img.shields.io/badge/AI_Code-Not_Detected-green)`;

  const scoreBar = buildScoreBar(qualityScore);

  const topIssues = summary.topQualityIssues.slice(0, 4);
  const topSignals = summary.topAiSignals.slice(0, 3);

  const fileTable = buildFileTable(fileAnalyses);

  const passFailSection = passed
    ? `> ✅ **This PR meets the minimum quality threshold of ${minScore}/100.**`
    : `> ❌ **This PR does not meet the minimum quality threshold of ${minScore}/100.** Please review the issues below and improve the contribution before merging.`;

  return `## 🔍 AI Contribution Quality Filter Report

${statusBadge} ${aiStatusBadge}

${passFailSection}

---

### 📊 Quality Score

${scoreEmoji} **${qualityScore} / 100**

${scoreBar}

| Metric | Value |
|--------|-------|
| Quality Score | **${qualityScore}/100** |
| AI Detection | **${aiDetected ? `Detected (${Math.round(aiConfidence * 100)}% confidence)` : "Not detected"}** |
| Files Analyzed | **${filesAnalyzed}** of ${totalFilesInPr} total files |
| Lines Added | **+${summary.totalLinesAdded}** |
| Lines Removed | **-${summary.totalLinesRemoved}** |
| Languages | **${summary.languagesDetected.join(", ") || "N/A"}** |
| Has Tests | **${summary.hasTests ? "✅ Yes" : "⚠️ Not detected"}** |

---

${aiDetected ? `### 🤖 AI Code Detection Signals

The following patterns suggest AI-generated code was present in this PR:

${topSignals.map((s) => `- ${s}`).join("\n") || "- General AI patterns detected"}

> *AI detection uses heuristic analysis of code patterns, naming conventions, comment styles, and structural indicators. False positives are possible.*

---

` : ""}${topIssues.length > 0 ? `### ⚠️ Quality Issues Detected

${topIssues.map((issue) => `- ${issue}`).join("\n")}

---

` : ""}### 📁 File Analysis Breakdown

${fileTable}

---

### 💡 How to Improve

${getImprovementTips(result)}

---

<details>
<summary>ℹ️ About this report</summary>

This report was generated by [AI Contribution Quality Filter](https://github.com/Noorislam-XD/AI-Contribution-Quality-Filter). 

The quality score (0-100) is calculated based on:
- **AI code detection** — heuristic analysis of patterns common in AI-generated code
- **Code size** — unusually large diffs are penalized
- **Error handling** — presence of try/catch and error handling patterns
- **Naming conventions** — quality of identifier names
- **Code duplication** — repeated blocks within the diff
- **Cyclomatic complexity** — estimated number of code branches

To configure thresholds or disable this action, see the [documentation](https://github.com/Noorislam-XD/AI-Contribution-Quality-Filter#readme).

</details>

*Generated at ${new Date().toUTCString()}*`;
}

function buildScoreBar(score: number): string {
  const filled = Math.round(score / 5);
  const empty = 20 - filled;
  const color = score >= 70 ? "🟩" : score >= 50 ? "🟨" : "🟥";
  return `\`[${"█".repeat(filled)}${"░".repeat(empty)}] ${score}%\``;
}

function getScoreEmoji(score: number): string {
  if (score >= 80) return "🌟";
  if (score >= 65) return "✅";
  if (score >= 50) return "⚠️";
  if (score >= 30) return "🔶";
  return "❌";
}

function buildFileTable(files: FileAnalysis[]): string {
  if (files.length === 0) return "_No files analyzed._";

  const rows = files
    .sort((a, b) => a.qualityScore - b.qualityScore)
    .slice(0, 15)
    .map((f) => {
      const scoreIcon =
        f.qualityScore >= 70 ? "🟢" : f.qualityScore >= 50 ? "🟡" : "🔴";
      const aiIcon =
        f.aiConfidence > 0.65 ? "🤖" : f.aiConfidence > 0.35 ? "⚠️" : "✅";
      const shortName =
        f.filename.length > 45
          ? "..." + f.filename.slice(-42)
          : f.filename;
      return `| \`${shortName}\` | ${f.language} | ${scoreIcon} ${f.qualityScore}/100 | ${aiIcon} ${Math.round(f.aiConfidence * 100)}% | +${f.linesAdded}/-${f.linesRemoved} |`;
    })
    .join("\n");

  return `| File | Language | Quality | AI Conf | Changes |
|------|----------|---------|---------|---------|
${rows}`;
}

function getImprovementTips(result: AnalysisResult): string {
  const tips: string[] = [];

  if (result.aiDetected) {
    tips.push("🤖 **Review AI-generated sections** — Ensure generated code is fully understood, tested, and adapted to your codebase.");
    tips.push("💬 **Remove AI-style comments** — Replace generic comments like \"This function...\" with meaningful context.");
  }

  if (!result.summary.hasTests) {
    tips.push("🧪 **Add tests** — Include unit or integration tests for new functionality.");
  }

  const hasErrorHandlingIssues = result.fileAnalyses.some((f) =>
    f.qualityDeductions.some((d) => d.category === "error_handling")
  );
  if (hasErrorHandlingIssues) {
    tips.push("🛡️ **Add error handling** — Wrap I/O operations, API calls, and risky logic in try/catch blocks.");
  }

  const hasDuplication = result.fileAnalyses.some((f) =>
    f.qualityDeductions.some((d) => d.category === "code_duplication")
  );
  if (hasDuplication) {
    tips.push("♻️ **Reduce duplication** — Extract repeated logic into reusable functions or utilities.");
  }

  const hasNamingIssues = result.fileAnalyses.some((f) =>
    f.qualityDeductions.some((d) => d.category === "naming")
  );
  if (hasNamingIssues) {
    tips.push("🏷️ **Improve naming** — Use descriptive, meaningful names for variables and functions.");
  }

  if (tips.length === 0) {
    tips.push("✨ **Great job!** This PR shows good code quality. Keep it up!");
  }

  return tips.map((t) => `- ${t}`).join("\n");
}
